###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'The Catalyst Project Team'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2024'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = True
external_toc_path = '_toc.yml'
gettext_additional_targets = ['literal-block']
gettext_compact = False
gettext_location = False
html_baseurl = ''
html_css_files = ['https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css']
html_favicon = 'media/logos/catalyst/favicon.ico'
html_last_updated_fmt = '%b %d, %Y'
html_logo = 'media/logos/hub-champion-training/text.svg'
html_show_copyright = True
html_sourcelink_suffix = ''
html_theme = 'sphinx_book_theme'
html_theme_options = {'toc_title': 'Table of contents.'}
html_title = 'Hub Champion Training'
language = 'en'
latex_engine = 'pdflatex'
locale_dirs = ['locale/']
myst_enable_extensions = ['amsmath', 'colon_fence', 'deflist', 'dollarmath', 'html_admonition', 'html_image', 'linkify', 'replacements', 'smartquotes', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'force'
nb_execution_timeout = 30
nb_output_stderr = 'show'
nb_render_priority = {'gettext': {}}
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
