name: Download translations from Crowdin

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    
permissions:
  contents: write
  pull-requests: write

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin download action
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n
          crowdin_branch_name: l10n
          skip_untranslated_files: true
          export_only_approved: true
          config: ./crowdin.yml          
          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_base_branch_name: 'main'    
          pull_request_labels: 'localization'
          pull_request_assignees: 'crowdin-bot'
          pull_request_reviewers: 'jnywong'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}